doctrine:
    dbal:
        connections:
            league:
                url: '%env(resolve:LEAGUE_DATABASE_URL)%'
                # Force the connection to be in latin1 charset.
                charset: latin1
                options:
                    1002: "SET NAMES 'latin1'"
            # Future plan is to use the league database as main
            # database, but with UTF-8 rather than latin1. In the
            # meantime, use a separate connection to the same
            # database with UTF-8.
            main:
                url: '%env(resolve:MAIN_DATABASE_URL)%'
        # TODO: Move to main.
        default_connection: main
    orm:
        default_entity_manager: main
        entity_managers:
            league:
                connection: league
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    League:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/League/Entity'
                        prefix: 'Nsv\League\Entity'
                        alias: League
            main:
                connection: main
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Dwz:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Dwz/Entity'
                        prefix: 'Nsv\Dwz\Entity'
                        alias: Dwz
                    Registration:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Registration/Entity'
                        prefix: 'Nsv\Registration\Entity'
                        alias: Registration
                    WebApp:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/WebApp/Entity'
                        prefix: 'Nsv\WebApp\Entity'
                        alias: WebApp

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
