doctrine:
    dbal:
        connections:
            webapp:
                url: '%env(resolve:WEBAPP_DATABASE_URL)%'
            league:
                url: '%env(resolve:LEAGUE_DATABASE_URL)%'
        default_connection: webapp    
    orm:
        default_entity_manager: webapp
        entity_managers:
            webapp:
                connection: webapp
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    WebApp:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/WebApp/Entity'
                        prefix: 'Nsv\WebApp\Entity'
                        alias: WebApp
            league:
                connection: league
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    League:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/League/Entity'
                        prefix: 'Nsv\League\Entity'
                        alias: League

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
