twig:
    default_path: '%kernel.project_dir%/src/WebApp/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    paths:
        '%kernel.project_dir%/src/League/templates': league

when@test:
    twig:
        strict_variables: true
