<?php

namespace Nsv\League\Repository;

use Nsv\League\Entity\League;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @extends ServiceEntityRepository<League>
 *
 * @method League|null find($id)
 */
class LeagueRepository extends ServiceEntityRepository
{
  public function __construct(ManagerRegistry $registry) {
    parent::__construct($registry, League::class);
  }

  // TODO: Might be autogenerated?
  public function findByPath(string $path): League|null {
    return $this->findOneBy(array('path' => $path));
  }

  // TODO: Delete
  public function persist(League $entity) {
    $this->getEntityManager()->persist($entity);
  }

  public function getEntityManager(): EntityManagerInterface {
    return parent::getEntityManager();
  }
}
