WebAppControllers:
    resource:
        path: ../src/WebApp/Controller/
        namespace: Nsv\WebApp\Controller
    type: attribute

LeagueControllers:
    resource:
        path: ../src/League/Controller/
        namespace: Nsv\League\Controller
    type: attribute
