# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $projectDir: '%kernel.project_dir%'

    _instanceof:
      Nsv\Util\Testing\Smoketest\SmoketestInterface:
        tags:
          - { name: monolog.logger, channel: smoketest }
          - { name: smoketest }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Nsv\WebApp\Command\:
        resource: '../src/WebApp/Command/'
    Nsv\WebApp\Controller\:
        resource: '../src/WebApp/Controller/'
    Nsv\WebApp\Core\:
        resource: '../src/WebApp/Core/'
    Nsv\WebApp\Core\WordPress\:
        resource: '../src/WebApp/Core/WordPress/'
    Nsv\WebApp\Repository\:
        resource: '../src/WebApp/Repository/'

    # League Manager services
    Nsv\League\Api\Service\:
        resource: '../src/League/Api/Service/'
    Nsv\League\Command\:
        resource: '../src/League/Command/'
    Nsv\League\Controller\:
        resource: '../src/League/Controller/'
    Nsv\League\Core\:
        resource: '../src/League/Core/'
    Nsv\League\Repository\:
        resource: '../src/League/Repository/'
    Nsv\League\Testing\:
      resource: '../src/League/Testing/'
    Nsv\League\Entity\League:
        factory: '@Nsv\League\Core\LeagueProvider'
    Nsv\League\Entity\Division:
        factory: '@Nsv\League\Core\DivisionProvider'
    Nsv\League\Core\LeagueAuthState:
        factory: ['@Nsv\League\Core\LeagueAuthProvider', 'authState']

    # Registration services
    Nsv\Registration\Controller\:
        resource: '../src/Registration/Controller/'
    Nsv\Registration\Repository\:
        resource: '../src/Registration/Repository/'

    # Rating & player database services
    Nsv\Dwz\:
        resource: '../src/Dwz/'
    Nsv\Dwz\Controller\:
        resource: '../src/Dwz/Controller/'

    #Util services
    Nsv\Util\Command\:
      resource: '../src/Util/Command/'
    Nsv\Util\Command\ExecuteSmoketestCommand:
      arguments:
        # inject all services that implement SmoketestInterface
        $smoketestInstances: !tagged_iterator smoketest
    Nsv\Util\MessageHandler\SmoketestMessageHandler:
      arguments:
        # inject all services that implement SmoketestInterface
        $smoketestInstances: !tagged_iterator smoketest
    Nsv\Util\Testing\:
      resource: '../src/Util/Testing/'

when@test:
    services:
        Nsv\League\Testing\:
            resource: '../src/League/Testing/'
            tags: ['doctrine.fixture.orm']
