<?php
// The navbar items are generated by the Bezirk's Wordpress installation
// Copy the JSON from the HTML source code comment into navbar.json to update.
function nsv2020_bezirk1_navbar() {
  $file = dirname(__FILE__) . '/navbar.json';
  return json_decode(file_get_contents($file), JSON_OBJECT_AS_ARRAY);
}
