name: phpunit

on:
  push:
    branches:
      - php-ci
    #paths:
    #  - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts
      - name: Start database
        run: |
          cd dev
          docker compose up -d database
      - name: Verify MySQL is up
        run: |
          for i in {1..5}; do
            nc -z 127.0.0.1 6465 && echo "MySQL is up" && exit 0
            sleep 2
          done
          echo "MySQL did not start in time" && exit 1
      - name: Prepare test fixtures
        run: |
          ./bin/console --env=test --em=league doctrine:fixtures:load
      - name: Run tests
        run: |
          ./bin/phpunit
      - name: Stop containers
        run: |
          cd dev
          docker compose down
