name: phpunit

on:
  push:
    branches:
      - php-ci
    #paths:
    #  - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      database:
        image: mysql:5.7
        ports:
          - 3306:3306"
        volumes:
          - ./dbinit:/docker-entrypoint-initdb.d
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: docker
          MYSQL_PASSWORD: docker
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Check databases
        run: mysql -h 127.0.0.1 -P 3306 -u root -proot -e 'SHOW DATABASES;'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts

      - name: Prepare test fixtures
        run: |
          ./bin/console --env=test --em=league doctrine:fixtures:load
      - name: Run tests
        run: |
          ./bin/phpunit
